#!/usr/bin/env python3
import re
import os

# Read original FP16 x_input.h
with open('inc/x_input.h', 'r') as f:
    fp16_vals = re.findall(r'0x[0-9a-fA-F]+', f.read())
    
print('='*80)
print('SOURCE DATA VERIFICATION')
print('='*80)
print('\nFP16 baseline (inc/x_input.h):')
print(f'  Total values: {len(fp16_vals)}')
print(f'  First 5: {fp16_vals[:5]}')
print()

# Check if mx_x_data.txt exists
if os.path.exists('golden-model/MX/mx_x_data.txt'):
    with open('golden-model/MX/mx_x_data.txt', 'r') as f:
        lines = [l.strip() for l in f if l.strip()]
    print('MX encoded data (golden-model/MX/mx_x_data.txt):')
    print(f'  Total lines: {len(lines)}')
    if lines:
        print(f'  First line length: {len(lines[0])} chars')
        print(f'  First line: {lines[0][:40]}...')
        print()
        print('VERDICT: ✓ MX data was GENERATED FROM the FP16 baseline')
        print()
        print('Generation command:')
        print('  python3 golden-model/MX/gen_mx_test_vectors.py \\')
        print('    --input inc/x_input.h \\')
        print('    --output-mx golden-model/MX/mx_x_data.txt \\')
        print('    ...')
else:
    print('⚠ MX data file not found')
    
print()
print('='*80)
print('CONCLUSION')
print('='*80)
print('YES - The MX inputs (x_input_mx.h, w_input_mx.h) are generated from')
print('      the same FP16 baseline data (x_input.h, w_input.h).')
print()
print('The pipeline is:')
print('  1. FP16 baseline generated by golden model (x_input.h, w_input.h)')
print('  2. MX encoder reads FP16 baseline and encodes to MX format')
print('  3. MX data written to mx_x_data.txt, mx_w_data.txt')
print('  4. C headers generated: x_input_mx.h, w_input_mx.h')
print()
print('So both modes start with THE SAME underlying FP16 data.')
