#!/bin/bash
# Performance summary collection script
# Runs FP16 and MX tests for various dimensions (N capped at 64)

OUTDIR="/scratch2/msc25h32/redmule/perf_results"
mkdir -p "$OUTDIR"

run_test() {
    local M=$1 N=$2 K=$3 MODE=$4  # MODE: fp16 or mx
    local LABEL="${M}x${N}x${K}_${MODE}"
    local LOGFILE="$OUTDIR/${LABEL}.log"

    echo "=== Running $LABEL ==="

    # Update tensor_dim.h
    cat > sw/inc/tensor_dim.h << EOF
 /* Header file generated by RedMulE Golden Model */
#ifndef __TENSOR_DIM__
#define __TENSOR_DIM__

#define M_SIZE  ${M}
#define N_SIZE  ${N}
#define K_SIZE  ${K}
#define SRC_FMT FP16
#define DST_FMT FP16
#define FPFORMAT 16
uint8_t gemm_ops = GEMM;

#endif
EOF

    # Generate golden
    make golden-clean > /dev/null 2>&1
    make golden OP=gemm M=$M N=$N K=$K > /dev/null 2>&1

    # Build SW
    if [ "$MODE" = "mx" ]; then
        make sw-build MX_ENABLE=1 target=vsim > /dev/null 2>&1
    else
        make sw-build target=vsim > /dev/null 2>&1
    fi

    if [ $? -ne 0 ]; then
        echo "  Result: BUILD_FAILED"
        echo "$LABEL|BUILD_FAILED|--|--|--|--|--|--|--|--" >> "$OUTDIR/summary.csv"
        return
    fi

    # Run sim
    timeout 360 make hw-run target=vsim > "$LOGFILE" 2>&1
    local RC=$?

    # Extract metrics
    local ERRORS=$(grep -oP 'errors=\K[0-9a-f]+' "$LOGFILE" | tail -1)
    local STALL_EVENTS=$(grep -oP '\[TB\]\[STALL\] events\s+:\s+\K\d+' "$LOGFILE")
    local STALL_CYCLES=$(grep -oP '\[TB\]\[STALL\] cycles\s+:\s+\K\d+' "$LOGFILE")
    local LOAD_STORE=$(grep -oP '\[PERF\] load->store cycles\s+:\s+\K\d+' "$LOGFILE")
    local TOTAL_CYCLES=$(grep -oP '\[PERF\] total cycles\s+:\s+\K\d+' "$LOGFILE")
    local ENGINE_CYCLES=$(grep -oP '\[PERF\] engine window cycles\s+:\s+\K\d+' "$LOGFILE")
    local CNT_RD=$(grep -oP '\[TB\] - cnt_rd=\K\d+' "$LOGFILE")
    local CNT_WR=$(grep -oP '\[TB\] - cnt_wr=\K\d+' "$LOGFILE")
    local PASS_FAIL=$(grep -oP '\[TB\] - \K(Pass|Fail)!' "$LOGFILE" | head -1)

    if [ $RC -eq 124 ]; then
        PASS_FAIL="TIMEOUT"
    fi

    # Handle missing values
    [ -z "$ERRORS" ] && ERRORS="--"
    [ -z "$STALL_EVENTS" ] && STALL_EVENTS="--"
    [ -z "$STALL_CYCLES" ] && STALL_CYCLES="--"
    [ -z "$LOAD_STORE" ] && LOAD_STORE="--"
    [ -z "$TOTAL_CYCLES" ] && TOTAL_CYCLES="--"
    [ -z "$ENGINE_CYCLES" ] && ENGINE_CYCLES="--"
    [ -z "$CNT_RD" ] && CNT_RD="--"
    [ -z "$CNT_WR" ] && CNT_WR="--"
    [ -z "$PASS_FAIL" ] && PASS_FAIL="--"

    echo "$LABEL|$PASS_FAIL|$ERRORS|$STALL_EVENTS|$STALL_CYCLES|$LOAD_STORE|$TOTAL_CYCLES|$ENGINE_CYCLES|$CNT_RD|$CNT_WR" >> "$OUTDIR/summary.csv"
    echo "  Result: $PASS_FAIL  errors=$ERRORS  total_cycles=$TOTAL_CYCLES"
}

# Header
echo "Test|Result|Errors|Stall_Ev|Stall_Cyc|L->S_Cyc|Total_Cyc|Engine_Cyc|cnt_rd|cnt_wr" > "$OUTDIR/summary.csv"

# Build HW once (shared between all runs)
#echo "Building HW..."
#make hw-build target=vsim > /dev/null 2>&1

# MX tests: M=32/64/96, N=64/128, K=64/96/128
for K in 64 96 128; do
  for M in 32 64 96; do
    for N in 64 128; do
      run_test $M $N $K mx
    done
  done
done

echo ""
echo "=== Summary ==="
column -t -s'|' "$OUTDIR/summary.csv"
